kind: Service
apiVersion: v1
metadata:
  #Service name
  name: wyco-app-svc
spec:
  selector:
    app: crane-cloud-272420
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
